#SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Novatek NT36xxx touchscreen driver.
#
# Each configuration option enables a list of files.

obj-y   += nt36xxx.o nt36xxx_fw_update.o nt36xxx_ext_proc.o nt36xxx_mp_ctrlram.o
obj-y	+= lct_ctp_selftest.o
obj-y	+= lct_tp_info.o
obj-y	+= lct_tp_work.o
obj-y	+= lct_tp_gesture.o
obj-y	+= lct_tp_grip_area.o