# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020)	+= fpc1020/
obj-$(CONFIG_FINGERPRINT_GF3208) += gf3208/